- eucaops/elbops.py
Proper discovery of test cert dir
> Fix for ELB SSL test

- eutester4j/TestSuites/GroovySuite.xml
- eutester4j/com/eucalyptus/tests/awssdk/Eutester4j.java
- eutester4j/com/eucalyptus/tests/awssdk/TestCFAdministration.groovy
- eutester4j/com/eucalyptus/tests/awssdk/TestEC2VPCDefaultVPC.groovy
- eutester4j/com/eucalyptus/tests/awssdk/TestEC2VPCManagement.groovy
- eutester4j/com/eucalyptus/tests/awssdk/TestELBVPC.groovy
- eutester4j/com/eucalyptus/tests/awssdk/TestSTSGetAccessToken.java
- eutester4j/com/eucalyptus/tests/awssdk/TestSTSGetImpersonationToken.java
I have a backlog with many groovy tests collected over the past 9 months. The barrier to ingressing them was that they were not E4J-iffied yet and required manually setting host ip, access key and secret key. They also were not ready to run via testng. I've updated E4J to have a minimal init method that will get just the host IP, access key and secret key from eucarc without creating all cloud connections images etc that getCloudInfo() does. getCloudInfo is still valuable for building tests from scratch. The existing groovy tests that I am and will be adding have been tweaked to use the new minimalInit method and have testng annotations.
> Initial commit of some backlogged groovy tests

- eutester4j/TestSuites/VPCSuite.xml
- eutester4j/com/eucalyptus/tests/awssdk/TestEC2VPCAssociationManagement.groovy
- eutester4j/com/eucalyptus/tests/awssdk/TestEC2VPCAttributeManagement.groovy
- eutester4j/com/eucalyptus/tests/awssdk/TestEC2VPCNetworkAclEntryManagement.groovy
- eutester4j/com/eucalyptus/tests/awssdk/TestEC2VPCNetworkInterfaces.groovy
- eutester4j/com/eucalyptus/tests/awssdk/TestEC2VPCSubnetAvailableAddresses.groovy
- eutester4j/com/eucalyptus/tests/awssdk/TestEC2VPCValidation.groovy
- eutester4j/com/eucalyptus/tests/awssdk/TestELBDefaultVPC.groovy
- eutester4j/com/eucalyptus/tests/awssdk/TestSWFSuccessWorkflow.groovy
- eutester4j/ivy.xml
Created a VPC test suite
Upped the AWS SDK version dep
> Add many new tests, mostly VPC.

- testcases/cloud_user/instances/bfebstest.py
Attach two volumes to a started instance and detach one after stop and anther after instance start.
Make sure that all volumes are deleted after StartStop test.
> Checks that a volume attached before stop operation can still be detached after instance is started.

- eutester4j/TestSuites/ELBSuite.xml
- eutester4j/TestSuites/IAMSuite.xml
- eutester4j/com/eucalyptus/tests/awssdk/TestELBAttributes.groovy
- eutester4j/ivy.xml
Current AWS Java SDK has api changes that would mean test changes. 
TODO: will revisit that later
Added some existing IAM tests to IAM test suite.
Added new ELB test and add it to ELB test list.
> Change AWS Java SDK version to 1.8.9

- eucaops/elbops.py
- eutester4j/TestSuites/CI-run.xml
- eutester4j/TestSuites/CloudWatchSuite.xml
Fixes running this test in CI.
test run in CI with the fix http://jenkins.qa1.eucalyptus-systems.com/job/eutester-test-load-balancing-ssl/415/console
> Change path to server cert dir

- testcases/cloud_user/autoscaling/autoscaling.py
Change-Id: I3adf216fea58fca5c912809e8b158df6121c34de
> Fail checking for scaling activities if there are none

- testcases/cloud_user/autoscaling/autoscaling.py
Change-Id: Iae5177c63796432a978014bb170a01b03b0be6f2
> Look for success status rather than 100 progress for ASG

- eutester4j/TestSuites/CI-run.xml
- eutester4j/TestSuites/S3Suite.xml
- eutester4j/com/eucalyptus/tests/awssdk/S3ListMpuTests.java
- eutester4j/com/eucalyptus/tests/awssdk/S3ListVersionsTests.java
- eutester4j/com/eucalyptus/tests/awssdk/S3MultiPartUploadTests.java
- eutester4j/com/eucalyptus/tests/awssdk/S3ObjectMultiDeleteTests.java
Tests for verifying EUCA-11513
> Add multi delete and other S3 tests

- eucaops/__init__.py
- eutester/euservice.py
Add temporary method to use the legacy creds scheme against future euca versions
> Add temporary method to use the legacy creds scheme for new clouds

- eutester4j/com/eucalyptus/tests/awssdk/TestEC2VPCNATGatewayManagement.groovy
EC2 VPC NAT gateway test covering management, filtering, lifecycle and some negative tests for gateways and related resources.
Related JIRA issue:
https://eucalyptus.atlassian.net/browse/EUCA-11980
> EC2 VPC NAT gateway management test.

- eutester4j/com/eucalyptus/tests/awssdk/TestEC2VPCRunInstanceNetworkInterfaces.groovy
Eutester4J tests covering running instances with multiple interfaces.
The test checks if VPC is available so should be safe to run on any cloud.
Related issues:
https://eucalyptus.atlassian.net/browse/EUCA-11800
https://eucalyptus.atlassian.net/browse/EUCA-11863
> EC2 VPC test for running instances with multiple network interfaces

- eutester4j/com/eucalyptus/tests/awssdk/TestCloudFormationELBAttributes.groovy
- eutester4j/com/eucalyptus/tests/awssdk/TestCloudFormationVPCAttributes.groovy
VPC test does not run instances so can be used in any network mode.
Related JIRA issues:
https://eucalyptus.atlassian.net/browse/EUCA-11762
https://eucalyptus.atlassian.net/browse/EUCA-11763
https://eucalyptus.atlassian.net/browse/EUCA-11765
https://eucalyptus.atlassian.net/browse/EUCA-11856
> CloudFormation tests for VPC and ELB

- eutester4j/com/eucalyptus/tests/awssdk/TestAutoScalingEC2InstanceTerminationProtection.groovy
- eutester4j/com/eucalyptus/tests/awssdk/TestEC2InstanceTerminationProtection.groovy
Tests covering EC2 and AutoScaling functionality related to EC2 instance termination protection.
> EC2 instance termination protection tests

- eutester4j/com/eucalyptus/tests/awssdk/TestEC2VPCRoutes.groovy
Test for routes with various destinations.
Related JIRA issue:
https://eucalyptus.atlassian.net/browse/EUCA-10821
> EC2 VPC route test for interface/instance/internet gateway destinations.

- eutester4j/com/eucalyptus/tests/awssdk/TestEC2VPCNetworkInterfaceAttach.groovy
Test for EC2 VPC network interface (ENI) attach and detach.
This test may need updating later depending on network interface attachment limits.
Related JIRA issue:
https://eucalyptus.atlassian.net/browse/EUCA-11864
> EC2 VPC network interface attach/detach test.

- eucaops/s3ops.py
- testcases/cloud_user/s3/bucket_tests.py
See issue https://github.com/eucalyptus/eutester/issues/377 for details.
> Fix test_bucket_acl and test_bucket_location tests

- testcases/cloud_admin/migration.py
-Add remote command exit code checks
-Move to new eserv-migrate-instance command(s)
> Migration test updates

- testcases/cloud_user/cloudformation/templates/autoscale.json
- testcases/cloud_user/cloudformation/templates/cfn-as-launchconfig-hvm.json
- testcases/cloud_user/cloudformation/templates/cfn-euca10286-template.json
- testcases/cloud_user/cloudformation/templates/cfn-euca9846-template.json
- testcases/cloud_user/cloudformation/templates/cfn-euca9965-template.json
- testcases/cloud_user/cloudformation/templates/cfn-ubuntu-docker.json
for key (KeyName) and image (ImageId)
> Updates to cloudformation templates unifying parameter names

- testcases/cloud_user/cloudformation/templates/autoscale.json
- testcases/cloud_user/cloudformation/templates/cfn-as-launchconfig-hvm.json
- testcases/cloud_user/cloudformation/templates/cfn-euca10286-template.json
- testcases/cloud_user/cloudformation/templates/cfn-euca9846-template.json
- testcases/cloud_user/cloudformation/templates/cfn-euca9965-template.json
- testcases/cloud_user/cloudformation/templates/cfn-ubuntu-docker.json
key pair = KeyName
image = ImageId
> Unify template parameter naming

- testcases/cloud_user/cloudformation/templates/wait-condition.json
No longer do apt-get update and or apt-get  install apache2 because it is a waste of time for this test
> For wait condition template fix signalurl in userdata so it works.

- testcases/cloud_user/cloudformation/templates/wait-condition.json
No longer do apt-get update and or apt-get install apache2 because it is a waste of time for this test
> For wait condition template fix signalurl in userdata so it works

- testcases/cloud_user/cloudformation/cloudformation_template_url_tests.py
Previously if the check timed out then the stack would not be deleted
> Do stack deletes in cleanup method

- eucaops/cfnops.py
- testcases/cloud_user/cloudformation/templates/cfn-euca9965-template.json
Also update cfn-euca9965 tempalte that does ELB + AS WebServer and uses CreationPolicy + ResourceSignal
> Add support for CAPABILITY_IAM for cloudformation templates
